package vehicles

import (
	"database/sql"
	"fmt"

	_ "github.com/lib/pq"
)

func NewStorage(user, password, dbname, sslmode string) (*sql.DB, error) {
	const operation = "storage.postgreSQL.New"
	connStr := fmt.Sprintf("user=%s password=%s dbname=%s sslmode=%s", user, password, dbname, sslmode)
	db, err := sql.Open("postgres", connStr)
	if err != nil {
		return nil, fmt.Errorf("%s.open:%w", operation, err)
	}

	stmt, err := db.Prepare(
		`CREATE TABLE IF NOT EXISTS vehicles(
		id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
		vin TEXT NOT NULL UNIQUE,
		brand TEXT NOT NULL,
		model TEXT NOT NULL,
		year integer NOT NULL,
		status TEXT NOT NULL,
		busy_until TIMESTAMP with time zone DEFAULT CURRENT_DATE);
	    `)
	if err != nil {
		return nil, fmt.Errorf("%s.prepare:%w", operation, err)
	}
	defer stmt.Close()
	if _, err = stmt.Exec(); err != nil {
		return nil, fmt.Errorf("%s.exec:%w", operation, err)
	}
	return db, nil
}
